name: grpc_web
description: Dart implementation of gRPC-Web.
version: 0.4.1
author: Wassim Vitols
homepage: https://github.com/wav/grpc-web-dart

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  meta: ^1.0.5
  grpc: ^0.4.1
  protobuf: ^0.7.2

dev_dependencies:
  test: ^0.12.0
